icons = "awesome"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"
# # enable_i3nagbar = false

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "focused_window"
max_width = 35

[[block]]
block = "music"
max_width = 10
buttons = ["prev", "play", "next"]

[[block]]
block = "weather"
format = "{weather} {temp}°"
# format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "ff919dde6e7244856542b3931b367a66", city_id = "5392952", units = "metric" }

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
# signal_strength = true
ip = false
speed_up = false
speed_down = false
# graph_up = true
# interval = 5
# use_bits = false

[[block]]
block = "cpu"
# on_click = "htop"
interval = 2

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "bluetooth"
mac = "00:02:5B:02:A5:9C"
# mac = "34:02:86:56:9B:8F"

[[block]]
block = "sound"
on_click = "pavucontrol-qt"

[[block]]
block = "backlight"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
# interval = 10
format = "{percentage}% {time}"
# format = "{percentage}% {power}W"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[theme]]
# name = "slick"
name = "solarized-dark"
[theme.overrides]

# ## Onedark theme
# idle_bg = "#282c34"
# idle_fg = "#c8ccd4"
# info_bg = "#abb2bf"
# info_fg = "#353b45"
# good_bg = "#98c379"
# # good_fg
# critical_bg = "#be5046"
# # critical_fg
# # separator
# # separator_bg
# # separator_fg
# warning_bg = "#c678dd"

# warning_fg
### Gruvbox dark hard
#idle_bg = "#1d2021"
#idle_fg = "#fbf1c7"
#info_bg = "#ebdbb2"
#info_fg = "#3c3836"
#good_bg = "#b8bb26"
## good_fg
#critical_bg = "#d65d0e"
## critical_fg
## separator
## separator_bg
## separator_fg
#warning_bg = "#d3869b"
## warning_fg


# Nord theme:
idle_bg = "#2e3440"
# idle_fg = "#98cff0"
idle_fg = "#e5e9f0"
info_bg = "#8fbcbb"
# info_bg = "#d8dee9"
info_fg = "#3b4252"
good_bg = "#8fbcbb"
# good_bg = "#a3be8c"
# good_fg
critical_bg = "#bf616a"
# critical_fg
# separator
# separator_bg
# separator_fg
warning_bg = "#b48ead"
# warning_fg
