#!/bin/bash
setbg() {
    cp "$1" "$HOME/.config/wall$2" && sh "$HOME/.fehbg" &
}

while read file
do
        case "$1" in
        "w") setbg $file 1 && setbg $file 2 ;;
        "1") setbg $file 1;;
        "2") setbg $file 2;;
        "c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | dmenu $DMENU_OPTIONS -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | dmenu $DMENU_OPTIONS -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"|")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu $DMENU_OPTIONS -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")	ifinstalled gimp && gimp "$file" & ;;
        esac
done
